### ISSUE TITLE
Failed build

### ISSUE THREAD

**Issue by yuanshuoastro** [soarlab/FPTuner#2] opened 2017-11-22 03:14 UTC
Dear FPTuner Team,

When building the code:

/usr/bin/ld: chcw.o: relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC

My system is Ubunt17.10 and python3.6. 

Could you help me?
 Best,

**Comment by keram88** [comment] 2017-11-22 04:37
I am able to reproduce your error. This is a defect in the FPTaylor component. It appears that either the system OCaml compiler is not configured properly or one of FPTaylor's components is not configured properly. I am investigating using a compiler installed by opam.

**Comment by keram88** [comment] 2017-11-23 00:04
I have reported this issue to the FPTaylor developers.
https://github.com/soarlab/FPTaylor/issues/12
FPTuner is known to build on Ubuntu 16.04, I suggest trying FPTuner on 16.04 while we work to fix FPTaylor.

**Comment by yuanshuoastro** [comment] 2017-11-23 16:06
Thank you @keram88 
I will focus on this topic.
Best,

**Comment by zvonimir** [comment] 2017-11-25 17:13
Since this is primarily an FPTaylor issue, I suggest we close it here.

**Closed as completed by zvonimir** 2017-11-25 17:13 UTC

**Comment by keram88** [comment] 2017-11-27 17:41
I'm sorry for giving you incorrect information @yuanshuoastro. FPTuner supports Ubuntu 14.04 at the moment.

**Comment by yuanshuoastro** [comment] 2017-11-29 13:45
Dear @keram88 
Sorry to disturb you again!
I just try to build and run on a Ubuntu 14.04. However I meet new problems and the examples does not work.

Could you help me? Thanks!



ubuntu@test2:~/FPTuner⟫ python3 setup.py install
sudo: unable to resolve host test2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libamd2.3.1 libcolamd2.8.0 libglpk36 libltdl7 python-ply
Suggested packages:
  libiodbc2-dev libmysqlclient-dev python-ply-doc
The following NEW packages will be installed:
  libamd2.3.1 libcolamd2.8.0 libglpk36 libltdl7 python-glpk python-ply
0 upgraded, 6 newly installed, 0 to remove and 4 not upgraded.
Need to get 578 kB of archives.
After this operation, 2311 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Abort.
sudo: unable to resolve host test2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libamd2.3.1 libcolamd2.8.0 libglpk36 libltdl7
Suggested packages:
  libiodbc2-dev libmysqlclient-dev
The following NEW packages will be installed:
  glpk-utils libamd2.3.1 libcolamd2.8.0 libglpk36 libltdl7
0 upgraded, 5 newly installed, 0 to remove and 4 not upgraded.
Need to get 556 kB of archives.
After this operation, 1818 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://nova.clouds.archive.ubuntu.com/ubuntu/ trusty/main libamd2.3.1 amd64 1:4.2.1-3ubuntu1 [23.5 kB]
Get:2 http://nova.clouds.archive.ubuntu.com/ubuntu/ trusty/main libcolamd2.8.0 amd64 1:4.2.1-3ubuntu1 [17.7 kB]
Get:3 http://nova.clouds.archive.ubuntu.com/ubuntu/ trusty/main libltdl7 amd64 2.4.2-1.7ubuntu1 [35.0 kB]
Get:4 http://nova.clouds.archive.ubuntu.com/ubuntu/ trusty/universe libglpk36 amd64 4.52.1-2build1 [384 kB]
Get:5 http://nova.clouds.archive.ubuntu.com/ubuntu/ trusty/universe glpk-utils amd64 4.52.1-2build1 [95.1 kB]
Fetched 556 kB in 0s (637 kB/s)  
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_TIME = "zh_CN.UTF-8",
        LC_MONETARY = "zh_CN.UTF-8",
        LC_ADDRESS = "zh_CN.UTF-8",
        LC_TELEPHONE = "zh_CN.UTF-8",
        LC_NAME = "zh_CN.UTF-8",
        LC_MEASUREMENT = "zh_CN.UTF-8",
        LC_IDENTIFICATION = "zh_CN.UTF-8",
        LC_NUMERIC = "zh_CN.UTF-8",
        LC_PAPER = "zh_CN.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_ALL to default locale: No such file or directory
Selecting previously unselected package libamd2.3.1:amd64.
(Reading database ... 59531 files and directories currently installed.)
Preparing to unpack .../libamd2.3.1_1%3a4.2.1-3ubuntu1_amd64.deb ...
Unpacking libamd2.3.1:amd64 (1:4.2.1-3ubuntu1) ...
Selecting previously unselected package libcolamd2.8.0:amd64.
Preparing to unpack .../libcolamd2.8.0_1%3a4.2.1-3ubuntu1_amd64.deb ...
Unpacking libcolamd2.8.0:amd64 (1:4.2.1-3ubuntu1) ...
Selecting previously unselected package libltdl7:amd64.
Preparing to unpack .../libltdl7_2.4.2-1.7ubuntu1_amd64.deb ...
Unpacking libltdl7:amd64 (2.4.2-1.7ubuntu1) ...
Selecting previously unselected package libglpk36:amd64.
Preparing to unpack .../libglpk36_4.52.1-2build1_amd64.deb ...
Unpacking libglpk36:amd64 (4.52.1-2build1) ...
Selecting previously unselected package glpk-utils.
Preparing to unpack .../glpk-utils_4.52.1-2build1_amd64.deb ...
Unpacking glpk-utils (4.52.1-2build1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up libamd2.3.1:amd64 (1:4.2.1-3ubuntu1) ...
Setting up libcolamd2.8.0:amd64 (1:4.2.1-3ubuntu1) ...
Setting up libltdl7:amd64 (2.4.2-1.7ubuntu1) ...
Setting up libglpk36:amd64 (4.52.1-2build1) ...
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
DEBUG = Some("false")
running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-msse3" "-O3" "-std=c++11" "-march=native" "-fno-lto" "-Wall" "-Wextra" "-o" "/home/ubuntu/FPTuner/gelpia/src/func/target/release/build/gr-5ce3c396d9ab3c4c/out/src/gaol_wrap.o" "-c" "src/gaol_wrap.cc"
cargo:warning=src/gaol_wrap.cc:3:23: fatal error: gaol/gaol.h: No such file or directory
cargo:warning= #include "gaol/gaol.h"
cargo:warning=                       ^
cargo:warning=compilation terminated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-msse3" "-O3" "-std=c++11" "-march=native" "-fno-lto" "-Wall" "-Wextra" "-o" "/home/ubuntu/FPTuner/gelpia/src/func/target/release/build/gr-5ce3c396d9ab3c4c/out/src/gaol_wrap.o" "-c" "src/gaol_wrap.cc" with args "c++" did not execute successfully (status code exit code: 1).

, /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670
note: Run with `RUST_BACKTRACE=1` for a backtrace.

make:  [src/func/comp_comm.sh] Error 101


Please set the environment variables: 

export HOME_FPTUNER=/home/ubuntu/FPTuner
export GELPIA_PATH=/home/ubuntu/FPTuner/gelpia
export GELPIA=/home/ubuntu/FPTuner/gelpia/bin/gelpia
export FPTAYLOR_BASE=/home/ubuntu/FPTuner/FPTaylor
export FPTAYLOR=/home/ubuntu/FPTuner/FPTaylor/fptaylor

Please append the environment variables: 

export PYTHONPATH=/home/ubuntu/FPTuner/src:/home/ubuntu/FPTuner/src/parser:$PYTHONPATH

Note: You must manually setup PYTHONPATH for Gurobi's python interface.
      Please refer to READMD.md and www.gurobi.com for more details.

The file fptuner_vars has been written which includes these variables. You may type
         source fptuner_vars
to set them.

`
ubuntu@test2:~/FPTuner⟫ ls
FPTaylor  LICENSE  README.md  Reference.md  bin  examples  fptuner_vars  gelpia  misc  setup.py  src
ubuntu@test2:~/FPTuner⟫ source fptuner_vars 
ubuntu@test2:~/FPTuner⟫ cd bin/
ubuntu@test2:~/FPTuner/bin⟫ ls
fptuner.py  test-table-5.1  test-table-5.2
ubuntu@test2:~/FPTuner/bin⟫ python3 ./fptuner.py -e 0.001 ../examples/helloworld0.py
Traceback (most recent call last):
  File "./fptuner.py", line 17, in <module>
    from input_to_tft import translate
  File "/home/ubuntu/FPTuner/src/parser/input_to_tft.py", line 3, in <module>
    from pass_utils import *
  File "/home/ubuntu/FPTuner/src/parser/pass_utils.py", line 65
    return (tag, *(expand(e, assigns, consts) for e in exp[1:]))
                    ^
SyntaxError: can use starred expression only as assignment target
1 ubuntu@test2:~/FPTuner/bin⟫ echo $PYTHONPATH 
/home/ubuntu/FPTuner/src:/home/ubuntu/FPTuner/src/parser:/home/ubuntu/gurobi652/linux64/lib/python3.4_utf32:
ubuntu@test2:~/FPTuner/bin⟫ 

`
